#!/bin/bash

# Offer 235 全面测试脚本
# 测试 V3 优化方案的所有功能

echo "=================================="
echo "🧪 Offer 235 全面测试"
echo "=================================="
echo ""

# 测试配置
OFFER_ID=235
BRAND="Eufy"
CATEGORY="Robot aspirapolvere e lavapavimenti"
COUNTRY="IT"
LANGUAGE="Italian"
URL="https://www.amazon.it/dp/B0DBVMD8Z8"
USER_ID=1

echo "📋 测试对象:"
echo "   Brand: $BRAND"
echo "   Category: $CATEGORY"
echo "   Country: $COUNTRY"
echo "   Language: $LANGUAGE"
echo "   URL: $URL"
echo ""

# 创建测试日志文件
LOG_FILE="/tmp/offer-235-test-$(date +%Y%m%d-%H%M%S).log"
echo "📝 测试日志: $LOG_FILE"
echo ""

# 测试1: 关键词数量验证
echo "=================================="
echo "🧪 测试1: 关键词数量验证"
echo "=================================="
echo "验证 AI 生成的关键词是否为 20-30 个"
echo ""
echo "预期结果:"
echo "  - 品牌词: 8-10个"
echo "  - 产品词: 6-8个"
echo "  - 购买词: 3-5个"
echo "  - 长尾词: 3-7个"
echo "  - 总计: 20-30个"
echo ""

# 测试2: 搜索量过滤验证
echo "=================================="
echo "🧪 测试2: 搜索量过滤验证"
echo "=================================="
echo "验证是否只过滤搜索量为0的关键词"
echo ""
echo "预期结果:"
echo "  - 所有关键词搜索量 > 0"
echo "  - 保留长尾词 (1-100/月)"
echo "  - 无搜索量关键词被过滤"
echo ""

# 测试3: 品牌词扩展验证
echo "=================================="
echo "🧪 测试3: 品牌词扩展验证"
echo "=================================="
echo "验证品牌词扩展是否都包含品牌名"
echo ""
echo "预期结果:"
echo "  - 所有品牌词都包含 'Eufy'"
echo "  - 所有品牌词都有搜索量 (> 0)"
echo "  - 不过滤竞争度"
echo ""

# 测试4: 竞争度保留验证
echo "=================================="
echo "🧪 测试4: 竞争度保留验证"
echo "=================================="
echo "验证是否保留了高竞争词"
echo ""
echo "预期结果:"
echo "  - 高竞争词占比: 20-30%"
echo "  - 竞争度不作为筛选条件"
echo "  - 所有有搜索量的关键词都保留"
echo ""

# 测试5: 缓存效果验证
echo "=================================="
echo "🧪 测试5: 缓存效果验证"
echo "=================================="
echo "验证 Redis 缓存是否正常工作"
echo ""
echo "预期结果:"
echo "  - 第一次查询: 调用 API (2-3秒)"
echo "  - 第二次查询: 从缓存返回 (50-100ms)"
echo "  - 缓存命中率: 70-90%"
echo "  - 缓存有效期: 7天"
echo ""

# 测试6: 灵活数量要求验证
echo "=================================="
echo "🧪 测试6: 灵活数量要求验证"
echo "=================================="
echo "验证是否根据市场情况灵活调整关键词数量"
echo ""
echo "预期结果:"
echo "  - 无最小数量强制"
echo "  - Eufy 在意大利: 15-25个关键词"
echo "  - 低搜索量市场: 5-15个关键词"
echo "  - 无数据市场: 显示警告"
echo ""

# 测试7: 日志输出验证
echo "=================================="
echo "🧪 测试7: 日志输出验证"
echo "=================================="
echo "验证日志输出是否清晰"
echo ""
echo "预期日志:"
echo "  ✅ 广告创意生成成功"
echo "  ⏱️ 获取关键词搜索量: XX个关键词"
echo "  🔧 已过滤 X 个无搜索量关键词"
echo "  🔍 使用Keyword Planner扩展品牌关键词"
echo "  ✅ 筛选出X个有效品牌关键词"
echo "  ✅ 关键词充足: XX个有真实搜索量的关键词"
echo ""

# 测试8: 性能指标验证
echo "=================================="
echo "🧪 测试8: 性能指标验证"
echo "=================================="
echo "验证性能指标是否符合预期"
echo ""
echo "预期指标:"
echo "  - 关键词生成时间: < 5秒"
echo "  - 缓存查询时间: 50-100ms"
echo "  - API 调用时间: 2-3秒"
echo "  - 总体响应时间: < 10秒"
echo ""

# 测试总结
echo "=================================="
echo "📊 测试总结"
echo "=================================="
echo ""
echo "✅ 所有测试用例已准备就绪"
echo ""
echo "下一步:"
echo "1. 启动开发服务器: npm run dev"
echo "2. 调用 API 生成广告创意"
echo "3. 查看日志输出"
echo "4. 验证关键词数量和质量"
echo "5. 验证缓存效果"
echo ""
echo "API 端点:"
echo "  POST /api/offers/[id]/generate-creatives"
echo ""
echo "请求体示例:"
echo "  {"
echo "    \"offerId\": 235,"
echo "    \"userId\": 1"
echo "  }"
echo ""
echo "=================================="
